"""Optional, data first schema and model inference."""

from .durable import (
    ResolvedFileSource,
    rebind_definition,
    register_source_factory,
    reopen_source_binding,
    resolve_source_binding,
    source_factory,
    unregister_file_source,
    unregister_source_factory,
    validate_source_binding,
    validate_source_binding_against_definition,
    validate_target_binding,
    validate_target_binding_against_definition,
)
from .facade import model_from_schema
from .records import infer_csv, infer_json, infer_records
from .sources import infer_source, infer_source_async
from .targets import (
    backfill_schema,
    check_write_compatibility,
    infer_records_for_target,
    infer_records_for_target_async,
    inspect_target,
    inspect_target_async,
    solve_backward_constraints,
)
from .transfer import forward_schema, infer_expression, infer_frame_schema
from .types import (
    FieldConstraint,
    InferenceLimits,
    InferenceObservation,
    InferenceResult,
    OutputProposal,
    ReplayHandle,
    SchemaEvidence,
    TargetObservation,
    WriteCompatibility,
)

__all__ = [
    "FieldConstraint",
    "InferenceLimits",
    "InferenceObservation",
    "InferenceResult",
    "OutputProposal",
    "ReplayHandle",
    "ResolvedFileSource",
    "SchemaEvidence",
    "TargetObservation",
    "WriteCompatibility",
    "backfill_schema",
    "check_write_compatibility",
    "forward_schema",
    "infer_csv",
    "infer_expression",
    "infer_frame_schema",
    "infer_json",
    "infer_records",
    "infer_records_for_target",
    "infer_records_for_target_async",
    "infer_source",
    "infer_source_async",
    "inspect_target",
    "inspect_target_async",
    "model_from_schema",
    "rebind_definition",
    "register_source_factory",
    "reopen_source_binding",
    "resolve_source_binding",
    "solve_backward_constraints",
    "source_factory",
    "unregister_file_source",
    "unregister_source_factory",
    "validate_source_binding",
    "validate_source_binding_against_definition",
    "validate_target_binding",
    "validate_target_binding_against_definition",
]
