"""Documented CLI exit codes (ETLantic 0.21)."""

from __future__ import annotations

SUCCESS = 0
GENERAL_FAILURE = 1
USAGE_ERROR = 2
INVALID_MODEL = 10
TRUST_FAILURE = 11
PLANNING_FAILURE = 12
EXECUTION_FAILURE = 13
PARTIAL_RUN = 14
BREAKING_CHANGE = 15
ENVIRONMENT_FAILURE = 16

__all__ = [
    "BREAKING_CHANGE",
    "ENVIRONMENT_FAILURE",
    "EXECUTION_FAILURE",
    "GENERAL_FAILURE",
    "INVALID_MODEL",
    "PARTIAL_RUN",
    "PLANNING_FAILURE",
    "SUCCESS",
    "TRUST_FAILURE",
    "USAGE_ERROR",
]
