"""etlantic init — scaffold a minimal import-safe pipeline project."""

from __future__ import annotations

import json
from pathlib import Path

import typer

from etlantic.project import write_minimal_etlantic_toml
from etlantic.workspace import ensure_workspace_layout, resolve_workspace

_PIPELINE_TEMPLATE = '''"""Minimal ETLantic pipeline (generated by etlantic init)."""

from etlantic import Data, Extract, Input, Load, Output, Pipeline, Transformation


class Row(Data):
    id: int
    name: str


class Identity(Transformation):
    rows: Input[Row]
    result: Output[Row]


@Identity.implementation("local")
def identity_local(rows: list[Row]) -> list[Row]:
    return list(rows)


class {pipeline_class}(Pipeline):
    raw: Extract[Row] = Extract(asset="rows")
    step = Identity.step(rows=raw)
    out: Load[Row] = Load(input=step.result, asset="out")
'''

_TEST_TEMPLATE = '''"""Tests for the generated pipeline."""

from {module_name} import {pipeline_class}


def test_pipeline_inspect() -> None:
    graph = {pipeline_class}.inspect()
    assert graph.pipeline_name == "{pipeline_class}"


def test_pipeline_validate() -> None:
    report = {pipeline_class}.validate(profile="development")
    assert report.valid
'''

_SAMPLE_DATA = [{"id": 1, "name": "Ada"}, {"id": 2, "name": "Grace"}]

_PROFILE_TEMPLATE = {
    "name": "development",
    "orchestrator": "local",
    "dataframe_engine": "local",
    "security_mode": "development",
    "validation_policy": "default",
    "assets": {
        "rows": "json://data/sample.json",
        "out": "json://data/out.json",
    },
}


def register_init_command(app: typer.Typer) -> None:
    @app.command("init")
    def init_cmd(
        directory: str = typer.Option(".", "--directory", "-d"),
        name: str = typer.Option("SamplePipeline", "--name"),
        profile: str = typer.Option("development", "--profile"),
        with_toml: bool = typer.Option(False, "--with-toml"),
        force: bool = typer.Option(False, "--force"),
    ) -> None:
        """Initialize a minimal import-safe pipeline and profile."""
        root = Path(directory).expanduser().resolve()
        if root.exists() and any(root.iterdir()) and not force:
            raise typer.BadParameter(
                f"Directory {root} is not empty. Use --force to overwrite scaffold files."
            )
        root.mkdir(parents=True, exist_ok=True)
        paths = resolve_workspace(workspace=root)
        ensure_workspace_layout(paths)
        (paths.reports / ".gitkeep").write_text("", encoding="utf-8")
        (paths.artifacts / ".gitkeep").write_text("", encoding="utf-8")

        pipeline_path = root / "pipeline.py"
        pipeline_path.write_text(
            _PIPELINE_TEMPLATE.format(pipeline_class=name),
            encoding="utf-8",
        )
        (paths.data / "sample.json").write_text(
            json.dumps(_SAMPLE_DATA, indent=2) + "\n",
            encoding="utf-8",
        )
        profiles_dir = root / "profiles"
        profiles_dir.mkdir(parents=True, exist_ok=True)
        profile_doc = dict(_PROFILE_TEMPLATE)
        profile_doc["name"] = profile
        (profiles_dir / f"{profile}.json").write_text(
            json.dumps(profile_doc, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        test_path = root / "test_pipeline.py"
        test_path.write_text(
            _TEST_TEMPLATE.format(module_name="pipeline", pipeline_class=name),
            encoding="utf-8",
        )
        if with_toml:
            write_minimal_etlantic_toml(
                root / "etlantic.toml",
                project=root.name,
                default_profile=profile,
            )

        target = f"pipeline.py:{name}"
        typer.echo(f"Initialized ETLantic project in {root}")
        typer.echo("")
        typer.echo("Next steps:")
        typer.echo(f"  etlantic doctor --profile {profile}")
        typer.echo(f"  etlantic inspect {target}")
        typer.echo(f"  etlantic validate {target} --profile {profile}")
        typer.echo(f"  etlantic plan {target} --profile {profile}")
        typer.echo(f"  etlantic run {target} --profile {profile}")
        typer.echo("  etlantic report list")
        typer.echo("  etlantic report show <run_id>")
