"""Control-plane identity, authorization, and scoped store protocols (CP1/CP2).

Public FastAPI-optional core surface. Import via::

    import etlantic as etl

    ctx = etl.control_plane.ControlPlaneContext(...)

or ``from etlantic.control_plane import ControlPlaneContext``.

FastAPI and SQLModel remain optional adapters; this package imports neither.
"""

from __future__ import annotations

from etlantic.control_plane.authz import (
    Disclosure,
    authorized_get_definition,
    map_deny_disclosure,
    raise_for_deny,
    require_authorized,
    require_authorized_run,
)
from etlantic.control_plane.durable_memory import MemoryDurableWorkStore
from etlantic.control_plane.durable_models import (
    ATTEMPT_RECORD_SCHEMA,
    BASELINE_ACK_SCHEMA,
    CHECKPOINT_RECORD_SCHEMA,
    DIFF_RECORD_SCHEMA,
    EFFECT_RECORD_SCHEMA,
    LEASE_RECORD_SCHEMA,
    OUTBOX_RECORD_SCHEMA,
    PREVIEW_WORKSPACE_SCHEMA,
    REPAIR_PLAN_SCHEMA,
    REPLAY_RECORD_SCHEMA,
    SHADOW_RUN_RECORD_SCHEMA,
    STATE_DIAGNOSTIC_SCHEMA,
    STATE_NAMESPACES,
    STATE_TRANSITION_EXPLANATION_SCHEMA,
    SUBMISSION_RECORD_SCHEMA,
    AttemptRecord,
    BaselineAcknowledgement,
    CheckpointRecord,
    DiffRecord,
    EffectRecord,
    LeaseRecord,
    OutboxRecord,
    PreviewWorkspace,
    RepairPlan,
    ReplayRecord,
    ShadowRunRecord,
    StateDiagnostic,
    StateTransitionExplanation,
    SubmissionRecord,
    namespaced_checkpoint_id,
)
from etlantic.control_plane.durable_protocols import DurableWorkStore
from etlantic.control_plane.errors import (
    CONTROL_PLANE_ERROR_SCHEMA,
    ControlPlaneError,
    ErrorDisclosure,
    ProblemDetails,
)
from etlantic.control_plane.history_memory import MemoryHistoryStore, MemoryImpactIndex
from etlantic.control_plane.history_models import (
    CACHE_INVALIDATION_EVENT_SCHEMA,
    IMPACT_EDGE_SCHEMA,
    PLAN_OBSERVATION_RECORD_SCHEMA,
    RELIABILITY_OBSERVATION_RECORD_SCHEMA,
    SCHEMA_OBSERVATION_RECORD_SCHEMA,
    CacheInvalidationEvent,
    ImpactEdge,
    ObservationKind,
    PlanObservationRecord,
    ReliabilityObservationRecord,
    SchemaObservationRecord,
    assert_history_metadata_only,
)
from etlantic.control_plane.history_protocols import HistoryStore, ImpactIndex
from etlantic.control_plane.memory import (
    MemoryAuthorizer,
    MemoryDefinitionRepository,
    MemoryEventStore,
    MemorySubmissionStore,
)
from etlantic.control_plane.models import (
    ACCEPT_RECEIPT_SCHEMA,
    CONTROL_PLANE_CONTEXT_SCHEMA,
    CONTROL_PLANE_EVENT_SCHEMA,
    SSE_CURSOR_SCHEMA,
    AcceptReceipt,
    AcceptResult,
    ControlPlaneContext,
    ControlPlaneEvent,
    CorrelationKey,
    EnvironmentRef,
    IdempotencyKey,
    Principal,
    SecurityDomain,
    TenantRef,
    WorkspaceRef,
)
from etlantic.control_plane.protocols import (
    Authorizer,
    AuthzDecision,
    DefinitionRepository,
    EventStore,
    SubmissionStore,
)
from etlantic.control_plane.redaction import (
    REDACTED,
    assert_no_secrets,
    redact_control_plane_payload,
    redact_control_plane_text,
)
from etlantic.control_plane.registry_definitions import (
    DEFINITION_KIND,
    RegistryDefinitionRepository,
)
from etlantic.control_plane.registry_memory import (
    MemoryRegistryProvider,
    MemoryRevisionRegistry,
    MemoryTenantDirectory,
    MemoryWorkspaceDirectory,
    content_fingerprint,
)
from etlantic.control_plane.registry_models import (
    ALIAS_RECORD_SCHEMA,
    ENVIRONMENT_RECORD_SCHEMA,
    LOGICAL_IDENTITY_SCHEMA,
    PROMOTION_RECORD_SCHEMA,
    REGISTRY_REVISION_SCHEMA,
    SECURITY_DOMAIN_RECORD_SCHEMA,
    TENANT_RECORD_SCHEMA,
    WORKSPACE_RECORD_SCHEMA,
    AliasRecord,
    EnvironmentRecord,
    LifecycleState,
    LogicalIdentity,
    PromotionRecord,
    RegistryRevision,
    SecurityDomainRecord,
    TenantRecord,
    WorkspaceRecord,
)
from etlantic.control_plane.registry_ops import (
    MemoryRetentionHook,
    RetentionHook,
    RevisionSearchHit,
    RevisionSearchPage,
    search_revisions,
)
from etlantic.control_plane.registry_protocols import (
    RegistryProvider,
    RevisionRegistry,
    TenantDirectory,
    WorkspaceDirectory,
)
from etlantic.control_plane.workspace_resources import (
    WORKSPACE_RESOURCE_RECORD_SCHEMA,
    MemoryWorkspaceResourceStore,
    WorkspaceResourceRecord,
    WorkspaceResourceStore,
    is_absolute_root_ref,
    reject_absolute_root_ref,
    reject_symlink_or_traversal,
    resolve_safe_root,
    validate_workspace_resource_record,
)

# CP4 — policy, approvals, quotas, objectives, erasure, attestation, audit
from etlantic.control_plane.approval_memory import MemoryApprovalStore
from etlantic.control_plane.approval_models import (
    APPROVAL_DECISION_SCHEMA,
    APPROVAL_REQUEST_SCHEMA,
    ApprovalDecisionRecord,
    ApprovalRequest,
)
from etlantic.control_plane.approval_protocols import ApprovalStore
from etlantic.control_plane.attestation_memory import MemoryAttestationStore
from etlantic.control_plane.attestation_models import (
    ATTESTATION_SCHEMA,
    SIGNED_SCHEMA_OBSERVATION_SCHEMA,
    VERIFICATION_RESULT_SCHEMA,
    Attestation,
    SignedSchemaObservation,
    VerificationResult,
    require_verified,
    sign_payload,
    verify_signature,
)
from etlantic.control_plane.attestation_protocols import AttestationStore
from etlantic.control_plane.audit_memory import MemoryAuditEvidenceStore
from etlantic.control_plane.audit_models import (
    AUDIT_EXPORT_SCHEMA,
    AUDIT_RECORD_SCHEMA,
    GENESIS_HASH,
    AuditExport,
    AuditRecord,
    compute_record_hash,
)
from etlantic.control_plane.audit_protocols import AuditEvidenceStore
from etlantic.control_plane.erasure_memory import (
    MemoryErasureProvider,
    MemoryErasureStore,
)
from etlantic.control_plane.erasure_models import (
    ERASURE_PLAN_SCHEMA,
    ERASURE_REPORT_SCHEMA,
    ERASURE_REQUEST_SCHEMA,
    ErasurePlan,
    ErasurePlanStep,
    ErasureReport,
    ErasureRequest,
    ErasureStepResult,
    assert_no_subject_values,
)
from etlantic.control_plane.erasure_protocols import ErasureProvider, ErasureStore
from etlantic.control_plane.governance_models import (
    GOVERNANCE_CONSTRAINTS_SCHEMA,
    GovernanceConstraints,
    merge_constraints,
)
from etlantic.control_plane.objective_memory import (
    MemoryNotificationProvider,
    MemoryObjectiveStore,
    memory_email_provider,
    memory_incident_provider,
    memory_slack_provider,
    memory_webhook_provider,
)
from etlantic.control_plane.objective_models import (
    DELIVERY_OBJECTIVE_SCHEMA,
    OBJECTIVE_EVALUATION_SCHEMA,
    OBJECTIVE_NOTIFICATION_SCHEMA,
    DeliveryObjective,
    ObjectiveEvaluation,
    ObjectiveNotification,
)
from etlantic.control_plane.objective_protocols import (
    NotificationProvider,
    ObjectiveStore,
)
from etlantic.control_plane.policy_gates import (
    enforce_policy_decision,
    evaluate_policy,
    gate_pre_plan,
    gate_pre_promote,
    gate_pre_submit,
)
from etlantic.control_plane.policy_memory import MemoryPolicyProvider
from etlantic.control_plane.policy_models import (
    POLICY_BUNDLE_SCHEMA,
    POLICY_DECISION_SCHEMA,
    PolicyBundle,
    PolicyDecision,
    compute_policy_fingerprint,
    decision_allows,
    decision_requires_approval,
)
from etlantic.control_plane.policy_opa import OpaPolicyProvider
from etlantic.control_plane.policy_protocols import PolicyProvider
from etlantic.control_plane.quota_memory import MemoryQuotaProvider
from etlantic.control_plane.quota_models import (
    QUOTA_BUDGET_SCHEMA,
    QUOTA_DECISION_SCHEMA,
    QUOTA_STATE_SCHEMA,
    QuotaBudget,
    QuotaDecision,
    QuotaState,
)
from etlantic.control_plane.quota_protocols import QuotaProvider

__all__ = [
    "ACCEPT_RECEIPT_SCHEMA",
    "ALIAS_RECORD_SCHEMA",
    "ATTEMPT_RECORD_SCHEMA",
    "BASELINE_ACK_SCHEMA",
    "CACHE_INVALIDATION_EVENT_SCHEMA",
    "CHECKPOINT_RECORD_SCHEMA",
    "CONTROL_PLANE_CONTEXT_SCHEMA",
    "CONTROL_PLANE_ERROR_SCHEMA",
    "CONTROL_PLANE_EVENT_SCHEMA",
    "DEFINITION_KIND",
    "DIFF_RECORD_SCHEMA",
    "EFFECT_RECORD_SCHEMA",
    "ENVIRONMENT_RECORD_SCHEMA",
    "IMPACT_EDGE_SCHEMA",
    "LEASE_RECORD_SCHEMA",
    "LOGICAL_IDENTITY_SCHEMA",
    "OUTBOX_RECORD_SCHEMA",
    "PLAN_OBSERVATION_RECORD_SCHEMA",
    "PREVIEW_WORKSPACE_SCHEMA",
    "PROMOTION_RECORD_SCHEMA",
    "REDACTED",
    "REGISTRY_REVISION_SCHEMA",
    "RELIABILITY_OBSERVATION_RECORD_SCHEMA",
    "REPAIR_PLAN_SCHEMA",
    "REPLAY_RECORD_SCHEMA",
    "SCHEMA_OBSERVATION_RECORD_SCHEMA",
    "SECURITY_DOMAIN_RECORD_SCHEMA",
    "SHADOW_RUN_RECORD_SCHEMA",
    "SSE_CURSOR_SCHEMA",
    "STATE_DIAGNOSTIC_SCHEMA",
    "STATE_NAMESPACES",
    "STATE_TRANSITION_EXPLANATION_SCHEMA",
    "SUBMISSION_RECORD_SCHEMA",
    "TENANT_RECORD_SCHEMA",
    "WORKSPACE_RECORD_SCHEMA",
    "WORKSPACE_RESOURCE_RECORD_SCHEMA",
    "AcceptReceipt",
    "AcceptResult",
    "AliasRecord",
    "AttemptRecord",
    "Authorizer",
    "AuthzDecision",
    "BaselineAcknowledgement",
    "CacheInvalidationEvent",
    "CheckpointRecord",
    "ControlPlaneContext",
    "ControlPlaneError",
    "ControlPlaneEvent",
    "CorrelationKey",
    "DefinitionRepository",
    "DiffRecord",
    "Disclosure",
    "DurableWorkStore",
    "EffectRecord",
    "EnvironmentRecord",
    "EnvironmentRef",
    "ErrorDisclosure",
    "EventStore",
    "HistoryStore",
    "IdempotencyKey",
    "ImpactEdge",
    "ImpactIndex",
    "LeaseRecord",
    "LifecycleState",
    "LogicalIdentity",
    "MemoryAuthorizer",
    "MemoryDefinitionRepository",
    "MemoryDurableWorkStore",
    "MemoryEventStore",
    "MemoryHistoryStore",
    "MemoryImpactIndex",
    "MemoryRegistryProvider",
    "MemoryRetentionHook",
    "MemoryRevisionRegistry",
    "MemorySubmissionStore",
    "MemoryTenantDirectory",
    "MemoryWorkspaceDirectory",
    "MemoryWorkspaceResourceStore",
    "ObservationKind",
    "OutboxRecord",
    "PlanObservationRecord",
    "PreviewWorkspace",
    "Principal",
    "ProblemDetails",
    "PromotionRecord",
    "RegistryDefinitionRepository",
    "RegistryProvider",
    "RegistryRevision",
    "ReliabilityObservationRecord",
    "RepairPlan",
    "ReplayRecord",
    "RetentionHook",
    "RevisionRegistry",
    "RevisionSearchHit",
    "RevisionSearchPage",
    "SchemaObservationRecord",
    "SecurityDomain",
    "SecurityDomainRecord",
    "ShadowRunRecord",
    "StateDiagnostic",
    "StateTransitionExplanation",
    "SubmissionRecord",
    "SubmissionStore",
    "TenantDirectory",
    "TenantRecord",
    "TenantRef",
    "WorkspaceDirectory",
    "WorkspaceRecord",
    "WorkspaceRef",
    "WorkspaceResourceRecord",
    "WorkspaceResourceStore",
    "assert_history_metadata_only",
    "assert_no_secrets",
    "authorized_get_definition",
    "content_fingerprint",
    "is_absolute_root_ref",
    "map_deny_disclosure",
    "namespaced_checkpoint_id",
    "raise_for_deny",
    "redact_control_plane_payload",
    "redact_control_plane_text",
    "reject_absolute_root_ref",
    "reject_symlink_or_traversal",
    "require_authorized",
    "require_authorized_run",
    "resolve_safe_root",
    "search_revisions",
    "validate_workspace_resource_record",
    # CP4
    "APPROVAL_DECISION_SCHEMA",
    "APPROVAL_REQUEST_SCHEMA",
    "ATTESTATION_SCHEMA",
    "AUDIT_EXPORT_SCHEMA",
    "AUDIT_RECORD_SCHEMA",
    "ApprovalDecisionRecord",
    "ApprovalRequest",
    "ApprovalStore",
    "Attestation",
    "AttestationStore",
    "AuditEvidenceStore",
    "AuditExport",
    "AuditRecord",
    "DELIVERY_OBJECTIVE_SCHEMA",
    "DeliveryObjective",
    "ERASURE_PLAN_SCHEMA",
    "ERASURE_REPORT_SCHEMA",
    "ERASURE_REQUEST_SCHEMA",
    "ErasurePlan",
    "ErasurePlanStep",
    "ErasureProvider",
    "ErasureReport",
    "ErasureRequest",
    "ErasureStepResult",
    "ErasureStore",
    "GENESIS_HASH",
    "GOVERNANCE_CONSTRAINTS_SCHEMA",
    "GovernanceConstraints",
    "MemoryApprovalStore",
    "MemoryAttestationStore",
    "MemoryAuditEvidenceStore",
    "MemoryErasureProvider",
    "MemoryErasureStore",
    "MemoryNotificationProvider",
    "MemoryObjectiveStore",
    "MemoryPolicyProvider",
    "MemoryQuotaProvider",
    "NotificationProvider",
    "OBJECTIVE_EVALUATION_SCHEMA",
    "OBJECTIVE_NOTIFICATION_SCHEMA",
    "ObjectiveEvaluation",
    "ObjectiveNotification",
    "ObjectiveStore",
    "OpaPolicyProvider",
    "POLICY_BUNDLE_SCHEMA",
    "POLICY_DECISION_SCHEMA",
    "PolicyBundle",
    "PolicyDecision",
    "PolicyProvider",
    "QUOTA_BUDGET_SCHEMA",
    "QUOTA_DECISION_SCHEMA",
    "QUOTA_STATE_SCHEMA",
    "QuotaBudget",
    "QuotaDecision",
    "QuotaProvider",
    "QuotaState",
    "SIGNED_SCHEMA_OBSERVATION_SCHEMA",
    "SignedSchemaObservation",
    "VERIFICATION_RESULT_SCHEMA",
    "VerificationResult",
    "assert_no_subject_values",
    "compute_policy_fingerprint",
    "compute_record_hash",
    "decision_allows",
    "decision_requires_approval",
    "enforce_policy_decision",
    "evaluate_policy",
    "gate_pre_plan",
    "gate_pre_promote",
    "gate_pre_submit",
    "memory_email_provider",
    "memory_incident_provider",
    "memory_slack_provider",
    "memory_webhook_provider",
    "merge_constraints",
    "require_verified",
    "sign_payload",
    "verify_signature",
]
